# site settings
title: Children's Bioinformatics Unit
pub_year: 2018
github_username: bi-ctsicn
theme: minima

# List of links in the navigation bar
navbar-links:
  Services: "service"
  People: "people"
  CBU Blog: "blog"

navbar-col: "#F5F5F5"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
  
