# site settings
title: Children's Bioinformatics Unit
pub_year: 2018
github_username: bi-ctsicn
theme: minima

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "CBU/images/ChildrensNational.jpg "

# List of links in the navigation bar
navbar-links:
  Services: "service"
  People: "people"
  CBU Blog: "blog"




plugins:
 - jekyll-feed
 - jekyll-seo-tag
  
