# site settings
title: CBU
pub_year: 2018
github_username: bi-ctsicn
theme: jekyll-theme-cayman

# List of links in the navigation bar
navbar-links:
  Services: "service"
  People: "people"
  CBU Blog: "blog"
  
