# site settings
title: CBU
pub_year: 2018
github_username: bi-ctsicn
theme: minima

# List of links in the navigation bar
navbar-links:
  Leadership: "leadership"
  Faculty And Staff: "facultyandstaff"
  CBU Blog: "blog"
  
