# site settings
title: Children's Bioinformatics Unit
pub_year: 2018
github_username: bi-ctsicn
theme: minima

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Services: "service"
  People: "people"
  CBU Blog: "blog"

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"



plugins:
 - jekyll-feed
 - jekyll-seo-tag
  
